### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Mryuanliu** [MrZJD/lumos#1]
hello你好，我想要做一个博客，觉得你的博客主题样式我非常喜欢，请问可以clone你的博客做二次开发吗？期待你的回复

**Comment by MrZJD** [comment]
哈喽你好
博客工具和主题都是开源的哦。
你可以搜一下，docsify 主题是docsify-themeable.

**Comment by Mryuanliu** [comment]
谢谢，你的博文也非常好，非常适合目前需要系统学习的我，嘿嘿😁，就不打扰你休息了，再次感谢
